#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/UnitTests.yml

  sql-tests:
    name: SQL Tests
    needs: unit-tests
    uses: ./.github/workflows/SQLTests.yml
    secrets:
      GSHEETS_KEY_FILE_JSON: ${{ secrets.GSHEETS_KEY_FILE_JSON }}

  duckdb-next-build:
    needs: sql-tests
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: gsheets
      exclude_archs: "windows_amd64_rtools"

  duckdb-stable-build:
    needs: sql-tests
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.4-andium
      ci_tools_version: main
      extension_name: gsheets
      exclude_archs: "windows_amd64_rtools"
